StudentApplication/Models/Course.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;

namespace StudentApplication.Models
{

    public class Student
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }

        public virtual List<Course> Courses { get; set; }
    }

    public class Course
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public int Unit { get; set; }
        public int StudentID { get; set; }
        public string Details { get; set; }

    }


    public static class _DB
    {
        public static int IdCounter;
        public static List<Student> Students { get; set; }

    }

}

StudentApplication/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentApplication.Models;

using TantaneLib;

namespace StudentApplication.Controllers
{
    public class CourseController : Controller
    {
        public ActionResult Details(int studentID, int courseID)
        {
            
            return View(_DB.Students.FirstOrDefault(s=>s.ID==studentID).Courses.FirstOrDefault(c=>c.ID==courseID));
        }

        // GET: Course/Create
        public ActionResult Create(int studentID)
        {
            return View(new Course() {StudentID = studentID });
        }

        public string totalCourseCount()
        {
            if (_DB.Students == null || _DB.Students.Count == 0)
                return "0";

            return "total course's counts: " + (from st in _DB.Students
                                                select st.Courses.Count).Sum().ToString();
        }

        [HttpPost]
        public ActionResult Create(Course course)
        {
            if (_DB.Students.FirstOrDefault(s => s.ID == course.StudentID).Courses == null)
                _DB.Students.FirstOrDefault(s => s.ID == course.StudentID).Courses = new List<Course>();


            course.ID = _DB.IdCounter++;
            _DB.Students.FirstOrDefault(s => s.ID == course.StudentID).Courses.Add(course);

            return Redirect("/student/Courses/?studentID=" + course.StudentID);
        }

        // GET: Course/Edit/5
        public ActionResult Edit(int studentID, int courseID)
        {
            return View(_DB.Students.FirstOrDefault(s => s.ID == studentID).Courses.FirstOrDefault(c=>c.ID==courseID));
        }

        // POST: Course/Edit/5
        [HttpPost]
        public ActionResult Edit(Course course)
        {
            Course cou= _DB.Students.FirstOrDefault(s => s.ID == course.StudentID).Courses.FirstOrDefault(c => c.ID == course.ID);
            cou.Details = course.Details;
            cou.Title = course.Title;
            cou.Unit = course.Unit;

            return Redirect("/course/minidetails/?studentID=" + course.StudentID+ "&courseID="+course.ID);
        }

        [HttpGet]
        public ActionResult Delete(int studentID, int courseID)
        {
            return View(_DB.Students.FirstOrDefault(s => s.ID == studentID).Courses.FirstOrDefault(c => c.ID == courseID));
        }

        [HttpPost]
        public ActionResult Delete(int studentID, int courseID,Course course)
        {
            Student stu = _DB.Students.FirstOrDefault(s => s.ID == studentID);
            Course cou = stu.Courses.FirstOrDefault(c => c.ID == courseID);
            stu.Courses.Remove(cou);

            return Redirect("~/student/Courses/?studentID=" + studentID +"&"+
                TanFieldsName.TanLayoutCloseState + "=" + TanLayoutCloseState.CloseAndRefereshDependentBlocks);
        }

        [HttpGet]
        public ActionResult MiniDetails(int studentID, int courseID)
        {
            return View(_DB.Students.FirstOrDefault(s => s.ID == studentID).Courses.FirstOrDefault(c => c.ID == courseID));
        }

    }
}

StudentApplication/Controllers/DragableUIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentApplication.Controllers
{
    public class DragableUIController : Controller
    {
        // GET: DragableUI
        public ActionResult Index()
        {
            return View();
        }



        public ActionResult window(int id=0)
        {

            ViewBag.id = id;
            
            return View();
        }



    }
}

StudentApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentApplication.Models;

using TantaneLib;

namespace StudentApplication.Controllers
{
    public class StudentController : Controller
    {
        
        public ActionResult Index()
        {
            if (_DB.Students==null)
                _DB.Students = new List<Student>();
            return View(_DB.Students);
        }


        public ActionResult Details(int id)
        {
            ViewBag.studentID = id;
            return View();
        }

        public ActionResult Details1(int id)
        {
            ViewBag.studentID = id;
            return View();
        }
        public ActionResult Details2(int id)
        {
            ViewBag.studentID = id;
            return View();
        }

        public ActionResult Courses(int studentID)
        {
            ViewBag.studentID = studentID;
            //return "studentId="+ studentID;
            return View(_DB.Students.FirstOrDefault(i => i.ID == studentID).Courses);
        }


        
        public ActionResult Create()
        {
            return View(new Student());
        }

        // POST: Home/Create
        [HttpPost]
        public ActionResult Create(Student student)
        {
            student.ID = _DB.IdCounter++;
            student.Courses=new List<Course>();
            _DB.Students.Add(student);
            return Redirect("~/student/Index?"+
                TanFieldsName.TanLayoutCloseState+"="+TanLayoutCloseState.CloseAndRefereshDependentBlocks);
            
        }

        public ActionResult Edit(int id)
        {
            return View(_DB.Students.FirstOrDefault(i=>i.ID==id));
        }

        // POST: Home/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Student student)
        {
            Student st =_DB.Students.FirstOrDefault(s => s.ID == id);
            st.Name = student.Name;
            st.Family = student.Family;
            return RedirectToAction("Index");
            
        }

        public ActionResult Delete(int id)
        {

            return View(_DB.Students.FirstOrDefault(i => i.ID == id));
        }

        // POST: Home/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Student student)
        {
            Student st = _DB.Students.FirstOrDefault(s => s.ID == id);
            _DB.Students.Remove(st);
            return RedirectToAction("Index");
        }
    }
}

StudentApplication/Controllers/otherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentApplication.Controllers
{
    public class otherController : Controller
    {
        // GET: other
        public ActionResult page2()
        {
            return View();
        }
        public ActionResult page3()
        {
            return View();
        }

        public String pageA()
        {
            return "this is pageA <br/> this is pageA <br/> this is pageA <br/> this is pageA <br/> this is pageA <br/> this is pageA <br/> this is pageA <br/> ";
        }

        public String pageB()
        {
            return "this is pageB <br/> this is pageB <br/> this is pageB <br/> this is pageB <br/>";
        }

        public String pageC()
        {
            return "this is pageC <br/> pageC <br/> pageC <br/> pageC <br/> pageC <br/> pageC <br/>pageC <br/>pageC <br/>pageC <br/>pageC <br/>pageC <br/>pageC <br/>pageC <br/>pageC <br/>";
        }
    }
}

StudentApplication/Views/Course/Create.cshtml
@model StudentApplication.Models.Course
@TantaneLib
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Unit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Unit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Unit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

StudentApplication/Views/Course/Delete.cshtml
@model StudentApplication.Models.Course

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this Course?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Details)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Details)
        </dd>

    </dl>
    
    <form action="/course/delete?studentID=@Model.StudentID&courseID=@Model.ID" method="post">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |

            <a href="~/course/minidetails?studentID=@Model.StudentID&courseID=@Model.ID&@TantaneLib.TanFieldsName.TanLayoutCloseState=@TantaneLib.TanLayoutCloseState.CloseWidthoutAnyReferesh">Back to List</a> |

        </div>
    </form>
</div>

StudentApplication/Views/Course/Details.cshtml
@model StudentApplication.Models.Course

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Details)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Details)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("courses", "Student", new { studentID= Model.StudentID})">Back to List</a> 

</p>

StudentApplication/Views/Course/Edit.cshtml
@model StudentApplication.Models.Course

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Unit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Unit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Unit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("minidetails", "course", new { studentID= Model.StudentID,courseID=Model.ID})">Cancel</a>
</div>

StudentApplication/Views/Course/MiniDetails.cshtml
@model StudentApplication.Models.Course
@using TantaneLib

<table width="100%">
    <tr>
        <td>
            @Html.DisplayFor(modelItem => Model.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.Unit)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.Details)
        </td>
        <td>
            <a href="@Url.Action("Edit", "Course", new { studentID= Model.StudentID, courseID=Model.ID })">Edit</a> |

            

        </td>
    </tr>
</table>

StudentApplication/Views/DragableUI/Index.cshtml
@using TantaneLib
@using StudentApplication.Models
@{
    ViewBag.Title = "Index";
}



<div style="border:1px solid red; float:right; width:200px; height:200px;">


    @if (_DB.Students != null)
    {
        foreach (var student in _DB.Students)
        {
            <a href="~/DragableUI/window?id=@student.ID&@TanHtmlHelper.Tan_Convert_to_SPA_Link(null, new TanLinkFeatures()
                                                 {
                                                     Target_Block = TanBlock.Block_in_Currentform("studentWindow" + student.ID.ToString())
                                                 })">Student_@student.ID</a> <br />
        }
        <hr />
    }

</div>




    @foreach (var student in _DB.Students)
    {
        @TanHtmlHelper.TanLoadSubpage(null, new TanBlockFeatures()
       {
           BlockName = "studentWindow" + student.ID.ToString(),
           Influence_Location_of_Browser =false
       })
    }









        <style>
            body {
                font-family: Arial, Helvetica, sans-serif;
            }

            table {
                font-size: 1em;
            }

            .ui-draggable, .ui-droppable {
                background-position: top;
            }
        </style>

StudentApplication/Views/DragableUI/window.cshtml
@using TantaneLib

@{ string dialogName = "dialog" + ViewBag.id;}

<div id="@dialogName" title="Basic dialog">
    @TanHtmlHelper.TanLoadSubpage(null, new TanBlockFeatures()
{
    BlockName = "DetailsWindow",
    Influence_Location_of_Browser = false,
    StaticURL= "/student/details?id="+ ViewBag.id
})
</div>


<script>
    $(function () {
        var id = '#'+'@dialogName';
        $(id).dialog();

        $(id).find(".tantane_block").tempUpdateBlocklinksAndFormsAfterContentChange();
    });


    

</script>

StudentApplication/Views/Shared/_Layout.cshtml
@using TantaneLib

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/Tantaneh.css" rel="stylesheet" />


    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    <script src="~/Scripts/jquery-ui.js"></script>
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Student", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Student", "Index", "Student")</li>
                    <li>@Html.ActionLink("Page2", "page2", "other")</li>
                    <li>@Html.ActionLink("Page3", "Page3", "other")</li>
                    <li>@Html.ActionLink("Multi_Windows", "index", "DragableUI")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">

        @using (@Html.TanMainWrapper())
        {
            @RenderBody()
        }

    </div>


    <br /><br /><br />
    <p>
        <hr/>
        @TanHtmlHelper.TanLoadSubpage(null, new TanBlockFeatures()
        {
            BlockName = "totalCourseCount",
            IsLayoutOrGlobal=true,
            StaticURL = "~/course/totalCourseCount",
            Influence_Location_of_Browser=false
        })
    </p>






   

    <script src="~/Scripts/tantaneh.js"></script>

</body>

</html>

StudentApplication/Views/Student/Courses.cshtml
@model IEnumerable<StudentApplication.Models.Course>
@using StudentApplication.Models
@using TantaneLib

@{
    ViewBag.Title = "Details";
}

<h2>
    @{
        Student st = _DB.Students.FirstOrDefault(s => s.ID == ViewBag.studentID);
        string nameFam = st.Name + " " + st.Family;
    }
    Courses of Student "@nameFam"
</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Unit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Details)
        </th>
        <th>Actions</th>
    </tr>
</table>
    @{ int i=0;}
    @foreach (var item in Model)
    {
        <hr style="margin:0px;" />
        @TanHtmlHelper.TanLoadSubpage(null, new TanBlockFeatures()
       {
           BlockName = "miniBlock"+i++,
           Influence_Location_of_Browser = false,
           StaticURL= "~/course/MiniDetails?studentID="+ViewBag.studentID+"&courseID="+item.ID
       })


        <a href="/course/delete?studentID=@item.StudentID&courseID=@item.ID@TanHtmlHelper.Tan_Convert_to_SPA_Link(null, new TanLinkFeatures()
            {
                Target_Block = TanBlock.Block_in_Currentform("courseBlock")
            })">Delete</a>


        <a href="@Url.Action("Details", "Course", new { studentID= ViewBag.studentID, courseID=item.ID })">Details</a>


        
                
    }



@TanHtmlHelper.TanLoadSubpage(null, new TanBlockFeatures()
{
    BlockName = "courseBlock",
    ShowAsOverlay = true,
    Influence_Location_of_Browser = true,
    Subsequent_BlockName_to_Referesh = TanBlock.Current_Form()
})

StudentApplication/Views/Student/Create.cshtml
@model StudentApplication.Models.Student

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Family, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Family, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Family, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="~/student/index?@TantaneLib.TanFieldsName.TanLayoutCloseState=@TantaneLib.TanLayoutCloseState.CloseWidthoutAnyReferesh">Back to List</a> 
</div>

StudentApplication/Views/Student/Delete.cshtml
@model StudentApplication.Models.Student

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Family)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Family)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StudentApplication/Views/Student/Details.cshtml
@using TantaneLib


<p>
    <form action="/course/create?studentID=@ViewBag.studentID" method="POST" target="@TanBlock.Block_in_Currentform("CoursesList")">
        <input type="hidden" name="StudentID" value="@ViewBag.studentID"><br>
        <table>
            <tr>
                <td>Title:</td>
                <td><input type="text" name="Title"></td>
            </tr>
            <tr>
                <td>Unit:</td>
                <td><input name="Unit" type="number" min="1"></td>
            </tr>
            <tr>
                <td>Details:</td>
                <td><input type="text" name="Details"></td>
            </tr>
        </table>
        <input type="submit" value="Create New Course">
    </form>

</p>

@TanHtmlHelper.TanLoadSubpage(null, new TanBlockFeatures()
{
    BlockName = "CoursesList",
    StaticURL = "~/student/Courses/?studentID=" + ViewBag.studentID,
    Subsequent_BlockName_to_Referesh = TanBlock.Block_in_Ancestor_Layout("totalCourseCount")

})

StudentApplication/Views/Student/Details1.cshtml
@using TantaneLib
@{
    ViewBag.Title = "Details1";
}

<h2>Details1</h2>

@TanHtmlHelper.TanLoadSubpage(null, new TanBlockFeatures()
{
    BlockName = "DetailsWrapper",
    StaticURL = "~/student/details/?id=" + ViewBag.studentID,
    Influence_Location_of_Browser=false
})

StudentApplication/Views/Student/Details2.cshtml
@using TantaneLib
@{
    ViewBag.Title = "Details2";
}

<h2>Details2</h2>

<a href="/student/details2?id=@ViewBag.studentID&@TanHtmlHelper.Tan_Convert_to_SPA_Link(null, new TanLinkFeatures()
                {
                    Target_Block = TanBlock.Block_in_Currentform("DetailsWrapper")
                })">Please Click here to page "Details" as an overlay (with_Url_History)</a> 

@TanHtmlHelper.TanLoadSubpage(null, new TanBlockFeatures()
{
    BlockName = "DetailsWrapper",
    StaticURL = "~/student/details/?id=" + ViewBag.studentID,
    ShowAsOverlay=true
})

StudentApplication/Views/Student/Edit.cshtml
@model StudentApplication.Models.Student
@using TantaneLib

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Family, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Family, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Family, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

StudentApplication/Views/Student/Index.cshtml
@model IEnumerable<StudentApplication.Models.Student>
@using TantaneLib

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
   
    <a href="/student/create?@TanHtmlHelper.Tan_Convert_to_SPA_Link(null, new TanLinkFeatures()
        {
            Target_Block = TanBlock.Block_in_Currentform("studentBlock")
        })"> Create New Student</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Family)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Family)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |



                <a href="/student/details1?id=@item.ID" class="btn btn-primary" role="button">Details1(without_Url_History)</a> |

                <a href="/student/details?id=@item.ID" class="btn btn-primary" role="button">Details(with_Url_History)</a> |


                <a href="/student/details?id=@item.ID&@TanHtmlHelper.Tan_Convert_to_SPA_Link(null, new TanLinkFeatures()
                {
                    Target_Block = TanBlock.Block_in_Currentform("studentBlock")
                })" class="btn btn-primary" role="button">Details(Overlay_without_Url_History)</a> |


                <a href="/student/details2?id=@item.ID" class="btn btn-primary" role="button">Details2(Overlay_with_Url_History)</a> |


                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>


@TanHtmlHelper.TanLoadSubpage(null, new TanBlockFeatures()
{
    BlockName = "studentBlock",
    ShowAsOverlay = true,
    Influence_Location_of_Browser = false,
    
    Subsequent_BlockName_to_Referesh = TanBlock.Current_Form()
})